"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Ctg_1 = require("./Ctg");
exports.Ctg = Ctg_1.default;
var Ecg_1 = require("./Ecg");
exports.Ecg = Ecg_1.default;
var Partogram_1 = require("./Partogram");
exports.Partogram = Partogram_1.default;
var WsService_1 = require("./services/WsService");
exports.WsService = WsService_1.WsService;
